### PR TITLE
Data Use Certification

### PR DESCRIPTION
**Pull request by casa1217**
Greetings,
Please review this section, see what you think.

### CODE REVIEW

**Comment by casa1217** [comment]
Shelia this is the final copy of the DUC for your review.

**Comment by smrgit** [comment]
Thanks, Ross.  In the very first section where you refer to GWAS data, I would just simplify that to "genomic data".  I didn't have time to check all of your links but I was wondering if you had looked at all of the related material that I think I had put on one or two of the slides from our NCI presentation (that day I was sick)?  I was thinking it might also be good to make the comparison between a PI's GCP project and their institutional IT system to make clear that their responsibilities are not very different.  In other words, that Google is not taking care of everything -- nor is the ISB-CGC ;-)

**Comment by casa1217** [comment]
Updated data

**Comment by casa1217** [comment]
Please see latest update and pull request.

**Comment by casa1217** [comment]
Sorry, had to correct a typo.

**Pull request merged**
