### PR TITLE
Add 3 new notebooks to HTAN Notebooks listing

### PR DESCRIPTION
**Pull request by clarisse-lau**

### CODE REVIEW

**Comment by clarisse-lau** [comment]
Hi @DeenaBleich , appreciate your review of this! 
Thanks!

**Review by DeenaBleich — COMMENTED** [review]
@clarisse-lau  Hi Clarisse, It looks ok to me. Please go ahead and merge.

**Review by DeenaBleich — COMMENTED** [review]
Actually, I'll merge the changes.

**Comment by clarisse-lau** [comment]
Thank you, @DeenaBleich ! :)

**Pull request merged**
